spring:
  cloud:
    stream:
      bindings:
        input:
          destination: order-events
          group: shipping-service
          
      rabbit:
        bindings:
          input:
            consumer:
              republish-to-dlq: true
              auto-bind-dlq: true
