spring:
  cloud:
    stream:
      bindings:
        input:
          destination: order-commands
          group: order-service
        output: 
          destination: order-events
        outputToError:
          destination: order-errors